site_name: Личная документация
site_url: https://IIShara.github.io
site_author: Ilgiz Sharafeev
site_description: Сборка шпаргалок и заметок

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml
    - shell

nav:
  - Главная: index.md
  - Заметки:
    - Синтаксис Markdown: Markdown.md
    - Основные команды Git: Git.md

  - Инструкции:
    - Keycloak: Keycloak.md
    - Prometheus: Prometheus.md
    - Ansible: Ansible.md
    - GitLab: GitLab.md
    - Kubernetes: K8s.md
    - Postgres + Patroni + etcd: postgres_etcd_patroni.md

  - Linux:
    - Мониторинг:
      - Top: Top.md
      - Vmstat: vmstat.md
    - Сборка пакетов:
      - Пересборка RPM пакета NGINX: RPM rebild.md