site_name: Личная документация
site_url: https://IIShara.github.io
site_author: Ilgiz Sharafeev
site_description: Сборка шпаргалок и заметок

theme:
  name: readthedocs
  highlightjs: true
  hljs_languages:
    - yaml

nav:
  - Главная: index.md
  - Шпаргалки:
    - Синтаксис Markdown: Markdown.md

